src/Entity/WeatherEntry.php
<?php

namespace App\Entity;

use App\Repository\WeatherEntryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WeatherEntryRepository::class)]
class WeatherEntry
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'weatherEntries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $temperature = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $feels_like_temperature = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $humidity = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $precipitation = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $wind_speed = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getFahrenheit(): ?float
    {
        $celsius = $this->getTemperature();

        if ($celsius === null) {
            return null;
        }

        return ($celsius * 9 / 5) + 32;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): static
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getFeelsLikeTemperature(): ?string
    {
        return $this->feels_like_temperature;
    }

    public function setFeelsLikeTemperature(string $feels_like_temperature): static
    {
        $this->feels_like_temperature = $feels_like_temperature;

        return $this;
    }

    public function getHumidity(): ?string
    {
        return $this->humidity;
    }

    public function setHumidity(string $humidity): static
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getPrecipitation(): ?string
    {
        return $this->precipitation;
    }

    public function setPrecipitation(string $precipitation): static
    {
        $this->precipitation = $precipitation;

        return $this;
    }

    public function getWindSpeed(): ?string
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(string $wind_speed): static
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }
}

src/Form/WeatherEntryType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\WeatherEntry;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WeatherEntryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('temperature')
            ->add('feels_like_temperature')
            ->add('humidity')
            ->add('precipitation')
            ->add('wind_speed')
            ->add('location', EntityType::class, [
                'class' => Location::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => WeatherEntry::class,
        ]);
    }
}

src/Controller/WeatherEntryController.php
<?php

namespace App\Controller;

use App\Entity\WeatherEntry;
use App\Form\WeatherEntryType;
use App\Repository\WeatherEntryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/weatherentry')]
class WeatherEntryController extends AbstractController
{
    #[IsGranted('ROLE_WEATHERENTRY_INDEX')]
    #[Route('/', name: 'app_weather_entry_index', methods: ['GET'])]
    public function index(WeatherEntryRepository $weatherEntryRepository): Response
    {
        return $this->render('weather_entry/index.html.twig', [
            'weather_entries' => $weatherEntryRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_WEATHERENTRY_NEW')]
    #[Route('/new', name: 'app_weather_entry_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $weatherEntry = new WeatherEntry();
        $form = $this->createForm(WeatherEntryType::class, $weatherEntry, [
            'validation_groups' => 'create'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($weatherEntry);
            $entityManager->flush();

            return $this->redirectToRoute('app_weather_entry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_entry/new.html.twig', [
            'weather_entry' => $weatherEntry,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_WEATHERENTRY_SHOW')]
    #[Route('/{id}', name: 'app_weather_entry_show', methods: ['GET'])]
    public function show(WeatherEntry $weatherEntry): Response
    {
        return $this->render('weather_entry/show.html.twig', [
            'weather_entry' => $weatherEntry,
        ]);
    }

    #[IsGranted('ROLE_WEATHERENTRY_EDIT')]
    #[Route('/{id}/edit', name: 'app_weather_entry_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, WeatherEntry $weatherEntry, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(WeatherEntryType::class, $weatherEntry, [
            'validation_groups' => 'edit'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_weather_entry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_entry/edit.html.twig', [
            'weather_entry' => $weatherEntry,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_WEATHERENTRY_DELETE')]
    #[Route('/{id}', name: 'app_weather_entry_delete', methods: ['POST'])]
    public function delete(Request $request, WeatherEntry $weatherEntry, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$weatherEntry->getId(), $request->request->get('_token'))) {
            $entityManager->remove($weatherEntry);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_weather_entry_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/weather_entry/_delete_form.html.twig
<form method="post" action="{{ path('app_weather_entry_delete', {'id': weather_entry.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ weather_entry.id) }}">
    <button class="btn">Delete</button>
</form>

templates/weather_entry/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/weather_entry/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WeatherEntry{% endblock %}

{% block body %}
    <h1>Edit WeatherEntry</h1>

    {{ include('weather_entry/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_weather_entry_index') }}">back to list</a>

    {{ include('weather_entry/_delete_form.html.twig') }}
{% endblock %}

templates/weather_entry/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherEntry index{% endblock %}

{% block body %}
    <h1>WeatherEntry index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Temperature</th>
                <th>Feels_like_temperature</th>
                <th>Humidity</th>
                <th>Precipitation</th>
                <th>Wind_speed</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for weather_entry in weather_entries %}
            <tr>
                <td>{{ weather_entry.id }}</td>
                <td>{{ weather_entry.date ? weather_entry.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ weather_entry.temperature }}</td>
                <td>{{ weather_entry.feelsLikeTemperature }}</td>
                <td>{{ weather_entry.humidity }}</td>
                <td>{{ weather_entry.precipitation }}</td>
                <td>{{ weather_entry.windSpeed }}</td>
                <td>
                    {% if is_granted('ROLE_WEATHERENTRY_SHOW') %}
                        <a href="{{ path('app_weather_entry_show', {'id': weather_entry.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_WEATHERENTRY_EDIT') %}
                        <a href="{{ path('app_weather_entry_edit', {'id': weather_entry.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_WEATHERENTRY_NEW') %}
        <a href="{{ path('app_weather_entry_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/weather_entry/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New WeatherEntry{% endblock %}

{% block body %}
    <h1>Create new WeatherEntry</h1>

    {{ include('weather_entry/_form.html.twig') }}

    <a href="{{ path('app_weather_entry_index') }}">back to list</a>
{% endblock %}

templates/weather_entry/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherEntry{% endblock %}

{% block body %}
    <h1>WeatherEntry</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ weather_entry.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ weather_entry.date ? weather_entry.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ weather_entry.temperature }}</td>
            </tr>
            <tr>
                <th>Feels_like_temperature</th>
                <td>{{ weather_entry.feelsLikeTemperature }}</td>
            </tr>
            <tr>
                <th>Humidity</th>
                <td>{{ weather_entry.humidity }}</td>
            </tr>
            <tr>
                <th>Precipitation</th>
                <td>{{ weather_entry.precipitation }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ weather_entry.windSpeed }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_weather_entry_index') }}">back to list</a>

    {% if is_granted('ROLE_WEATHERENTRY_EDIT') %}
        <a href="{{ path('app_weather_entry_edit', {'id': weather_entry.id}) }}">edit</a>
    {% endif %}

    {% if is_granted('ROLE_WEATHERENTRY_DELETE') %}
        {{ include('weather_entry/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}